# worker06.acme.com         Ready    worker            8d    v1.18.2   pool=oil
# only run on pool=oil
---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: oil
spec:
  owners:
  - name: alice
    kind: User
  nodeSelector:
    pool: oil
    kubernetes.io/os: linux